### ISSUE TITLE
Err: java.lang.NullPointerException (Rus)

### ISSUE THREAD

**Issue by kaliziya** [sinnlabs/dbvim#13]
В существующей форме, после внесения небольших изменений начала появляться ошибка:
Неизвестное исключение: java.lang.NullPointerException.

Так же было выяснено, что в настройках самой формы сохранились не существующие филды (ранее удаленные).

**Comment by nsa-a1** [comment]
fixed. de057b30c08333652cb7126b14ffb618911be89b
