### ISSUE TITLE
Err TableFields if add colum (Rus)

### ISSUE THREAD

**Issue by kaliziya** [sinnlabs/dbvim#16]
Настроил элемент TableFields, указав поля имеющие данные. Решил добавить перспективное поле, в котором пока нет данных. Сохранил, открываю форму, произвожу поиск и получаю результат с ошибкой: "Unable to raise onEntryLoaded event."
Закрываю ошибку, смотрю все поля выгрузились, но в TableFields пусто. Там же нажимаю кнопку Refresh и появляется ошибка: "Неизвестное исключение: java.lang.NullPointerException."

**Comment by nsa-a1** [comment]
Root cause: TableField incorrectly handles null values.
Fixed in c77381ba43b4c7b41543d329b8af79f8750d0276
