### ISSUE TITLE
TableField. Edit tableColumns. Sort Columns. (Rus)

### ISSUE THREAD

**Issue by kaliziya** [sinnlabs/dbvim#17]
При повторном редактировании отображающихся колонок, сортировка ранее выбранных колонок сбрасывается на алфавитную. Т.е.:
1. нажал кнопку edit tablecolumns
2. смотрю порядок ранее выбранных изменился. Отредактировал как надо. Сохранил.
3. повторно открываю, снова порядок не верный.

**Comment by kaliziya** [comment]
Такая же фигня в пропертис самой формы. Сортировка сбивается.

**Comment by nsa-a1** [comment]
fixed: dc166ffa5fa5952381f1bf002ad9f353fbf6dd72
