### ISSUE TITLE
URL by id (Rus)

### ISSUE THREAD

**Issue by kaliziya** [sinnlabs/dbvim#18]
Есть две, как мне видится, связанные задачи:
1. Необходим механизм получения прямой ссылки на запись
2. Есть две формы: ф1 и ф2. Формы имеют связанные данные, например по SiteID. В ф.1. я нашел нужный мне SiteID, и теперь хочу нажав кнопку увидеть связанные с этим SiteID ф2. Как мне настроить такую кнопку?

**Comment by nsa-a1** [comment]
Fixed. 31a974946a60c58bf67320d9ade8950b7121dda6
