### ISSUE TITLE
Advance data search (Rus)

### ISSUE THREAD

**Issue by kaliziya** [sinnlabs/dbvim#19]
При написании формулы в расширенном поиске нужно указывать id поля, но за частую id поля и имя поля не сопоставимы.
Было бы удобно сделать авто заполнение при нажатии на нужное поле, ну или как минимум выпадающий список всех возможных полей, ведь некоторые поля могут быть скрыты.

**Comment by nsa-a1** [comment]
Fixed 3d9b2a62e80ffb3862189b911893ee231df4f7f5
