### ISSUE TITLE
event handlers are not displayed on the Events tab (Rus)

### ISSUE THREAD

**Issue by kaliziya** [sinnlabs/dbvim#23]
При просмотре ранее созданного выпадающего меню, в разделе Event пустые данные, хотя в form definition скрипт присутствует.

**Comment by nsa-a1** [comment]
Event handler is displayed on the Events tab, but not diplayed in the expand window

**Comment by nsa-a1** [comment]
Fixed in 97cc65096d3dc055c7a520de96d77f46a2b2618b
