### ISSUE TITLE
Tabbox. Move tabbox component in tree. Bug. (Rus)

### ISSUE THREAD

**Issue by kaliziya** [sinnlabs/dbvim#6]
Сделал я такой форму, прям супер красивую.
там у нас юзается Tabbox
изначально я сделал так:
Tabbox
-tabpaneles
--tabpanel
--tabpanel
--tabpanel
-tabs
--tab
--tab
--tab

Ну я такой думаю, чет у меня задом наперед, сперва панели, а потом только табы. Ну я сохранил форму. Потом беру такой и перетаскиваю tabs и втыкаю перед tabpanel (insert before)

И все, пиздец, форма не пашет.
Ок думаю, я же сохранялся. Я такой обновляю все странички, открываю форму. И пиздец. форма убита, древо функций не отображается. И т.п. Если открыть форму на вью, то куча ява ошибок. 

Пробовал на другом компе, тажа хня.

**Comment by nsa-a1** [comment]
Проблема была в том, что ты выставил свойство selectedIndex в tabbox.
